package typeMappings;

import com.google.common.collect.ImmutableTable;
import enums.Type;

public final class TypeMapping {

    private TypeMapping() {
        throw new RuntimeException("Default constructor suppressed for non-instantiability.");
    }

    // Parameterized as Attacker, Defender, Multiplier
    public static final ImmutableTable<Type, Type, Double> typeMapping =
            new ImmutableTable.Builder<Type, Type, Double>()
                    .put(Type.Bug, Type.Fire, .5)
                    .put(Type.Bug, Type.Grass, 2.0)
                    .put(Type.Bug, Type.Fighting, .5)
                    .put(Type.Bug, Type.Poison, .5)
                    .put(Type.Bug, Type.Flying, .5)
                    .put(Type.Bug, Type.Psychic, 2.0)
                    .put(Type.Bug, Type.Ghost, .5)
                    .put(Type.Bug, Type.Dark, 2.0)
                    .put(Type.Bug, Type.Steel, .5)
                    .put(Type.Bug, Type.Fairy, .5)
                    .put(Type.Dark, Type.Dark, .5)
                    .put(Type.Dark, Type.Fairy, .5)
                    .put(Type.Dark, Type.Fighting, .5)
                    .put(Type.Dark, Type.Ghost, 2.0)
                    .put(Type.Dark, Type.Psychic, 2.0)
                    .put(Type.Dragon, Type.Dragon, 2.0)
                    .put(Type.Dragon, Type.Fairy, 0.0)
                    .put(Type.Dragon, Type.Steel, .5)
                    .put(Type.Electric, Type.Dragon, .5)
                    .put(Type.Electric, Type.Electric, .5)
                    .put(Type.Electric, Type.Flying, 2.0)
                    .put(Type.Electric, Type.Grass, .5)
                    .put(Type.Electric, Type.Ground, 0.0)
                    .put(Type.Electric, Type.Water, 2.0)
                    .put(Type.Fairy, Type.Dark, 2.0)
                    .put(Type.Fairy, Type.Dragon, 2.0)
                    .put(Type.Fairy, Type.Fighting, 2.0)
                    .put(Type.Fairy, Type.Fire, .5)
                    .put(Type.Fairy, Type.Poison, .5)
                    .put(Type.Fairy, Type.Steel, .5)
                    .put(Type.Fighting, Type.Bug, .5)
                    .put(Type.Fighting, Type.Dark, 2.0)
                    .put(Type.Fighting, Type.Fairy, .5)
                    .put(Type.Fighting, Type.Flying, .5)
                    .put(Type.Fighting, Type.Ghost, 0.0)
                    .put(Type.Fighting, Type.Ice, 2.0)
                    .put(Type.Fighting, Type.Normal, 2.0)
                    .put(Type.Fighting, Type.Poison, .5)
                    .put(Type.Fighting, Type.Psychic, .5)
                    .put(Type.Fighting, Type.Rock, 2.0)
                    .put(Type.Fighting, Type.Steel, 2.0)
                    .put(Type.Fire, Type.Bug, 2.0)
                    .put(Type.Fire, Type.Dragon, .5)
                    .put(Type.Fire, Type.Fire, .5)
                    .put(Type.Fire, Type.Grass, 2.0)
                    .put(Type.Fire, Type.Ice, 2.0)
                    .put(Type.Fire, Type.Rock, .5)
                    .put(Type.Fire, Type.Steel, 2.0)
                    .put(Type.Fire, Type.Water, .5)
                    .put(Type.Flying, Type.Bug, 2.0)
                    .put(Type.Flying, Type.Electric, .5)
                    .put(Type.Flying, Type.Fighting, 2.0)
                    .put(Type.Flying, Type.Grass, 2.0)
                    .put(Type.Flying, Type.Rock, .5)
                    .put(Type.Flying, Type.Steel, .5)
                    .put(Type.Ghost, Type.Dark, .5)
                    .put(Type.Ghost, Type.Ghost, 2.0)
                    .put(Type.Ghost, Type.Normal, 0.0)
                    .put(Type.Ghost, Type.Psychic, 2.0)
                    .put(Type.Grass, Type.Bug, .5)
                    .put(Type.Grass, Type.Dragon, .5)
                    .put(Type.Grass, Type.Fire, .5)
                    .put(Type.Grass, Type.Flying, .5)
                    .put(Type.Grass, Type.Grass, .5)
                    .put(Type.Grass, Type.Ground, 2.0)
                    .put(Type.Grass, Type.Poison, .5)
                    .put(Type.Grass, Type.Rock, 2.0)
                    .put(Type.Grass, Type.Steel, .5)
                    .put(Type.Grass, Type.Water, 2.0)
                    .put(Type.Ground, Type.Bug, .5)
                    .put(Type.Ground, Type.Electric, 2.0)
                    .put(Type.Ground, Type.Fire, 2.0)
                    .put(Type.Ground, Type.Flying, 0.0)
                    .put(Type.Ground, Type.Grass, .5)
                    .put(Type.Ground, Type.Poison, 2.0)
                    .put(Type.Ground, Type.Rock, 2.0)
                    .put(Type.Ground, Type.Steel, 2.0)
                    .put(Type.Ice, Type.Dragon, 2.0)
                    .put(Type.Ice, Type.Fire, .5)
                    .put(Type.Ice, Type.Flying, 2.0)
                    .put(Type.Ice, Type.Grass, 2.0)
                    .put(Type.Ice, Type.Ground, 2.0)
                    .put(Type.Ice, Type.Ice, .5)
                    .put(Type.Ice, Type.Steel, .5)
                    .put(Type.Ice, Type.Water, .5)
                    .put(Type.Normal, Type.Ghost, 0.0)
                    .put(Type.Normal, Type.Rock, .5)
                    .put(Type.Normal, Type.Steel, .5)
                    .put(Type.Poison, Type.Fairy, 2.0)
                    .put(Type.Poison, Type.Ghost, .5)
                    .put(Type.Poison, Type.Grass, 2.0)
                    .put(Type.Poison, Type.Ground, .5)
                    .put(Type.Poison, Type.Rock, .5)
                    .put(Type.Poison, Type.Poison, .5)
                    .put(Type.Poison, Type.Steel, 0.0)
                    .put(Type.Psychic, Type.Dark, 0.0)
                    .put(Type.Psychic, Type.Fighting, 2.0)
                    .put(Type.Psychic, Type.Poison, 2.0)
                    .put(Type.Psychic, Type.Psychic, .5)
                    .put(Type.Psychic, Type.Steel, .5)
                    .put(Type.Rock, Type.Fire, 2.0)
                    .put(Type.Rock, Type.Ice, 2.0)
                    .put(Type.Rock, Type.Fighting, .5)
                    .put(Type.Rock, Type.Ground, .5)
                    .put(Type.Rock, Type.Flying, 2.0)
                    .put(Type.Rock, Type.Bug, 2.0)
                    .put(Type.Rock, Type.Steel, .5)
                    .put(Type.Steel, Type.Fairy, 2.0)
                    .put(Type.Steel, Type.Fire, .5)
                    .put(Type.Steel, Type.Grass, .5)
                    .put(Type.Steel, Type.Ice, 2.0)
                    .put(Type.Steel, Type.Rock, 2.0)
                    .put(Type.Steel, Type.Steel, .5)
                    .put(Type.Steel, Type.Water, .5)
                    .put(Type.Water, Type.Dragon, .5)
                    .put(Type.Water, Type.Fire, 2.0)
                    .put(Type.Water, Type.Grass, .5)
                    .put(Type.Water, Type.Ground, 2.0)
                    .put(Type.Water, Type.Rock, 2.0)
                    .put(Type.Water, Type.Water, .5)
                    .build();
}
